services:
  webapi:
    build:  
      context: .
      dockerfile: Dockerfile
    image: BookLoanApp
    ports:
      - "5003:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development
      - IMAGE_SAVE_PATH=/app/Images
    volumes:
      - ./Images:/app/Images
    depends_on:
      - mysql.railway.internal