services:
    webapi:
      build:  
         context: .
         dockerfile: Dockerfile
      image: BookLoanApp
      ports:
         - "5003:80"
      environment:
         - ASPNETCORE_URLS=http://+:80
         - ASPNETCORE_ENVIRONMENT=Development
        
      depends_on:
          - postgres.railway.internal

    postgreserver:
      image: postgres:latest
      environment:
        POSTGRES_DB: railway
        POSTGRES_USER: postgres
       

        
      ports:
        - "5432:5432"
      volumes:
          - pgdata:/var/lib/postgresql/data/pgdata


volumes:
    pgdata: