services:
    webapi:
      build:  
         context: .
         dockerfile: Dockerfile
      image: BookLoanApp
      ports:
         - "5003:80"
      environment:
         - ASPNETCORE_URLS=http://+:80
         - ASPNETCORE_ENVIRONMENT=Development
        
      depends_on:
          - mysql.railway.internal

